// ── TodoFloat Theme Presets ──────────────────────────────────────────────────
// Every theme defines ALL CSS variables completely — fully self-contained.
// glitch: true enables cyberpunk glitch effects via a CSS class on <html>

const THEMES = {

    // ── Default Dark ─────────────────────────────────────────────────────────
    default: {
        label: 'Default',
        preview: ['#0f0f12', '#7c6af7', '#1e1e27'],
        glitch: false,
        vars: {
            '--bg': '#0f0f12',
            '--bg2': '#17171d',
            '--bg3': '#1e1e27',
            '--surface': '#1a1a22',
            '--surface2': '#222230',
            '--border': '#2e2e3e',
            '--accent': '#7c6af7',
            '--accent2': '#9d8fff',
            '--accent-glow': 'rgba(124,106,247,.25)',
            '--text': '#e8e8f0',
            '--text2': '#9090a8',
            '--text3': '#5a5a72',
            '--red': '#ff5e6c',
            '--yellow': '#f5c842',
            '--green': '#4ecb71',
            '--shadow': '0 8px 40px rgba(0,0,0,.6)',
            '--font': "'DM Sans', sans-serif",
            '--radius': '14px',
            '--radius-sm': '8px',
            '--body-bg': '#17171d',
            '--input-bg': '#1e1e27',
            '--modal-bg': '#17171d',
            '--dropdown-bg': '#17171d',
            '--settings-bg': '#17171d',
            '--toggle-off': '#1e1e27',
        }
    },

    // ── Designer — warm cream light ──────────────────────────────────────────
    designer: {
        label: 'Designer',
        preview: ['#fdf8f4', '#f4623a', '#f0e6d8'],
        glitch: false,
        vars: {
            '--bg': '#fdf8f4',
            '--bg2': '#ffffff',
            '--bg3': '#f5ede4',
            '--surface': '#ffffff',
            '--surface2': '#ede4da',
            '--border': '#e0d0c0',
            '--accent': '#f4623a',
            '--accent2': '#ff8a65',
            '--accent-glow': 'rgba(244,98,58,.2)',
            '--text': '#2c1a10',
            '--text2': '#8a6a58',
            '--text3': '#c0a898',
            '--red': '#e53935',
            '--yellow': '#f9a825',
            '--green': '#43a047',
            '--shadow': '0 8px 40px rgba(0,0,0,.10)',
            '--font': "'DM Sans', sans-serif",
            '--radius': '20px',
            '--radius-sm': '12px',
            '--body-bg': '#ffffff',
            '--input-bg': '#ffffff',
            '--modal-bg': '#ffffff',
            '--dropdown-bg': '#ffffff',
            '--settings-bg': '#ffffff',
            '--toggle-off': '#e0d0c0',
        }
    },

    // ── Coder — true black, matrix green ────────────────────────────────────
    coder: {
        label: 'Coder',
        preview: ['#080808', '#00e676', '#111111'],
        glitch: false,
        vars: {
            '--bg': '#080808',
            '--bg2': '#0e0e0e',
            '--bg3': '#161616',
            '--surface': '#111111',
            '--surface2': '#1a1a1a',
            '--border': '#262626',
            '--accent': '#00e676',
            '--accent2': '#69f0ae',
            '--accent-glow': 'rgba(0,230,118,.2)',
            '--text': '#e0ffe8',
            '--text2': '#5a8a5a',
            '--text3': '#2e4a2e',
            '--red': '#ff1744',
            '--yellow': '#ffea00',
            '--green': '#00e676',
            '--shadow': '0 8px 32px rgba(0,0,0,.9)',
            '--font': "'DM Mono', monospace",
            '--radius': '4px',
            '--radius-sm': '2px',
            '--body-bg': '#0e0e0e',
            '--input-bg': '#161616',
            '--modal-bg': '#0e0e0e',
            '--dropdown-bg': '#0e0e0e',
            '--settings-bg': '#0e0e0e',
            '--toggle-off': '#161616',
        }
    },

    // ── Cyberpunk — near-black purple, neon yellow, glitch effects ───────────
    cyberpunk: {
        label: 'Cyberpunk',
        preview: ['#08040f', '#ffe600', '#1a0030'],
        glitch: true,
        vars: {
            '--bg': '#08040f',
            '--bg2': '#0e0818',
            '--bg3': '#180a28',
            '--surface': '#120620',
            '--surface2': '#1e0e38',
            '--border': '#36106a',
            '--accent': '#ffe600',
            '--accent2': '#ff2d78',
            '--accent-glow': 'rgba(255,230,0,.2)',
            '--text': '#fff0ff',
            '--text2': '#b060d8',
            '--text3': '#5a2080',
            '--red': '#ff2d78',
            '--yellow': '#ffe600',
            '--green': '#39ff14',
            '--shadow': '0 8px 40px rgba(255,230,0,.06)',
            '--font': "'DM Mono', monospace",
            '--radius': '2px',
            '--radius-sm': '0px',
            '--body-bg': '#0e0818',
            '--input-bg': '#180a28',
            '--modal-bg': '#0e0818',
            '--dropdown-bg': '#0e0818',
            '--settings-bg': '#0e0818',
            '--toggle-off': '#180a28',
        }
    },

};